class LocalizationService {
  static const Map<String, Map<String, String>> _localizedValues = {
    'ar': {
      'app_name': 'نقي',
      'filter_control': 'التحكم في الفلتر',
      'filter_active': 'الفلتر نشط',
      'filter_inactive': 'الفلتر غير نشط',
      'sensitivity': 'الحساسية',
      'filtered_scenes': 'المشاهد المفلترة',
      'quiet_mode': 'وضع الهدوء',
      'parental_mode': 'وضع الوالدين',
      'set_pin': 'تعيين رمز PIN',
      'enter_pin': 'أدخل رمز PIN',
      'verify_pin': 'تحقق من رمز PIN',
      'low': 'منخفضة',
      'medium': 'متوسطة',
      'high': 'عالية',
      'settings': 'الإعدادات',
      'about': 'حول',
      'privacy': 'الخصوصية',
      'help': 'مساعدة',
      'app_description': 'تطبيق نقي يعمل على فلترة المحتوى غير اللائق تلقائيًا لحماية خصوصيتك',
      'processing_offline': 'المعالجة محليًا - بدون إنترنت',
      'notification_cleaned': 'تم تنظيف الشاشة - Naqi Active 🌿',
      'activate_filter': 'تفعيل الفلتر',
      'deactivate_filter': 'إيقاف الفلتر',
      'sensitivity_low': 'حساسية منخفضة - يسمح بمحتوى أكثر',
      'sensitivity_medium': 'حساسية متوسطة - متوازن',
      'sensitivity_high': 'حساسية عالية - أكثر صرامة',
    },
    'en': {
      'app_name': 'Naqi',
      'filter_control': 'Filter Control',
      'filter_active': 'Filter Active',
      'filter_inactive': 'Filter Inactive',
      'sensitivity': 'Sensitivity',
      'filtered_scenes': 'Filtered Scenes',
      'quiet_mode': 'Quiet Mode',
      'parental_mode': 'Parental Mode',
      'set_pin': 'Set PIN',
      'enter_pin': 'Enter PIN',
      'verify_pin': 'Verify PIN',
      'low': 'Low',
      'medium': 'Medium',
      'high': 'High',
      'settings': 'Settings',
      'about': 'About',
      'privacy': 'Privacy',
      'help': 'Help',
      'app_description': 'Naqi app automatically filters inappropriate content to protect your privacy',
      'processing_offline': 'Processing Locally - No Internet',
      'notification_cleaned': 'Screen Cleaned - Naqi Active 🌿',
      'activate_filter': 'Activate Filter',
      'deactivate_filter': 'Deactivate Filter',
      'sensitivity_low': 'Low Sensitivity - Allow More',
      'sensitivity_medium': 'Medium Sensitivity - Balanced',
      'sensitivity_high': 'High Sensitivity - Strict',
    },
  };

  static String get(String key, String locale) {
    final lang = locale.split('_')[0];
    return _localizedValues[lang]?[key] ?? key;
  }
}
